name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Get project code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t test-app .

      - name: Tag docker image
        run: docker tag cicd-practice:latest 510869689698.dkr.ecr.eu-central-1.amazonaws.com/test-app:latest

      - name: Push docker image to ECR
        run: docker push 510869689698.dkr.ecr.eu-central-1.amazonaws.com/test-app:latest