name: Deploy to ECS

permissions:
  id-token: write
  contents: read


on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Get project code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::510869689698:role/GitHubActionsECRRole
          aws-region: eu-central-1

      - name: Build docker image
        run: docker build -t test-app .

      - name: Tag docker image
        run: docker tag test-app:latest 510869689698.dkr.ecr.eu-central-1.amazonaws.com/cicd-practice:latest

      - name: Push docker image to ECR
        run: docker push 510869689698.dkr.ecr.eu-central-1.amazonaws.com/cicd-practice:latest