name: Terraform Check

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./terraform

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Get project code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::510869689698:role/GitHubActionsTerraformRole
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan


      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve